version: "1.0"
services:
  mongodb:
    image: "mongo"
    env_file:
      - .env

  server:
    container_name: mern-server
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env

  client:
    container_name: mern-client
    build: ./frontend
    ports:
      - "5000:3000"
    depends_on:
      - server
