version: '1.0'
services:
  mongodb:
    image: "mongo"
  server:
    container_name: mern-server
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  client:
    container_name: mern-client
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

